### ISSUE TITLE
App crashes when applying/changing highlight or font color

### ISSUE THREAD

**Issue by NathanBnm** [phase1geo/Outliner#22]
The selected color (hihglight or font) is saved but the app crashes.

Here is the output in the console:

```
GLib-GObject-WARNING **: 10:58:56.763: g_object_notify: object class 'GtkLabel' has no property named 'rgba'
Segmentation fault
``` 

And when changing font color when there is already an highlight color:
```
Gtk-CRITICAL **: 11:01:53.314: gtk_widget_shape_combine_region: assertion '_gtk_widget_get_has_window (widget)' failed
Segmentation fault
```

I'm running the development version.

**Comment by phase1geo** [comment]
I have fixed issues with the highlight and font coloring in the development branch.  This will be generally available in the next stable release (1.1).

**Comment by NathanBnm** [comment]
I still have the issue with the latest development version. Idk if it's due to some residual cache on my PC or not.

**Comment by phase1geo** [comment]
I can no longer replicate this issue with existing outliner files. I also tried recreating it with a fresh install and could not see any issues there.
